{"name": "test_create_obj[data3]", "status": "failed", "statusDetails": {"message": "AssertionError: Object with id ff8081818eeb2234018eef9d81cf0f75 wasn't deleted", "trace": "data = {'data': {'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA', 'price': 2805.99, 'year': 1982}, 'name': 'DKA_4'}, create_new_obj_endpoint = <endpoints.create_obj.CreateObject object at 0x0000024098F02E10>\ndel_obj_by_id_endpoint = <endpoints.delete_obj.DeleteObject object at 0x0000024098F54560>\n\n    @pytest.mark.parametrize(\"data\", TEST_DATA)\n    def test_create_obj(data, create_new_obj_endpoint, del_obj_by_id_endpoint):\n        create_new_obj_endpoint.create_new_obj(data)\n        create_new_obj_endpoint.check_obj_name(data['name'])\n>       create_new_obj_endpoint.del_obj()\n\ntests\\test_some_app.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <endpoints.create_obj.CreateObject object at 0x0000024098F02E10>\n\n    @allure.step('Удаление объекта.')\n    def del_obj(self):\n        self.response = requests.delete(\n            f\"{self.url}/{self.obj_json['id']}\"\n        )\n        self.response = requests.get(\n            f\"{self.url}/{self.obj_json['id']}\")\n>       assert self.response.status_code == 404, f\"Object with id {self.obj_json['id']} wasn't deleted\"\nE       AssertionError: Object with id ff8081818eeb2234018eef9d81cf0f75 wasn't deleted\n\nendpoints\\create_obj.py:32: AssertionError"}, "steps": [{"name": "Создаем новый объект.", "status": "passed", "parameters": [{"name": "body", "value": "{'name': 'DKA_4', 'data': {'year': 1982, 'price': 2805.99, 'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA'}}"}], "start": 1713417060255, "stop": 1713417060924}, {"name": "Проверяем имя созданного объекта.", "status": "passed", "parameters": [{"name": "name", "value": "'DKA_4'"}], "start": 1713417060925, "stop": 1713417060925}, {"name": "Удаление объекта.", "status": "failed", "statusDetails": {"message": "AssertionError: Object with id ff8081818eeb2234018eef9d81cf0f75 wasn't deleted\n", "trace": "  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\test_api_dka\\endpoints\\create_obj.py\", line 32, in del_obj\n    assert self.response.status_code == 404, f\"Object with id {self.obj_json['id']} wasn't deleted\"\n"}, "start": 1713417060925, "stop": 1713417062367}], "parameters": [{"name": "data", "value": "{'name': 'DKA_4', 'data': {'year': 1982, 'price': 2805.99, 'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA'}}"}], "start": 1713417060255, "stop": 1713417062368, "uuid": "76912cda-2673-4235-b31a-8ece6cc6b8dc", "historyId": "54f8bbec902703f377efdd3851833eed", "testCaseId": "446c5770a8159f9ad79dc3323a217e9b", "fullName": "tests.test_some_app#test_create_obj", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_some_app"}, {"name": "host", "value": "Kirill"}, {"name": "thread", "value": "21760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_some_app"}]}