{"uuid": "443a0c39-22e0-4120-9303-28f7bfa6eafc", "children": ["ba8f97de-15df-4432-8c44-40d3200d054e"], "befores": [{"name": "create_obj", "status": "failed", "statusDetails": {"message": "AssertionError: Object {'name'} wasn't created.\n", "trace": "  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\test_api_dka\\conftest.py\", line 41, in create_obj\n    create_new_obj_endpoint.check_obj_name({\"name\"})\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\test_api_dka\\endpoints\\create_obj.py\", line 23, in check_obj_name\n    assert self.obj_json['name'] == name, f\"Object {name} wasn't created.\"\n"}, "steps": [{"name": "Создаем новый объект.", "status": "passed", "parameters": [{"name": "body", "value": "{'name': 'New_obj_DKA2805', 'data': {'year': 1982, 'price': 2805.99, 'CPU model': 'Intel Core i9DKA', 'Hard disk size': '1 TB DKA'}}"}], "start": 1713417423695, "stop": 1713417424537}, {"name": "Проверяем имя созданного объекта.", "status": "failed", "statusDetails": {"message": "AssertionError: Object {'name'} wasn't created.\n", "trace": "  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\test_api_dka\\endpoints\\create_obj.py\", line 23, in check_obj_name\n    assert self.obj_json['name'] == name, f\"Object {name} wasn't created.\"\n"}, "parameters": [{"name": "name", "value": "{'name'}"}], "start": 1713417424537, "stop": 1713417424537}], "start": 1713417423695, "stop": 1713417424538}], "start": 1713417423695, "stop": 1713417424632}